name: Build and Test

on:
  push:
    tags-ignore:
      - '*.*'
    branches:
      - main
  pull_request:

jobs:
  server:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - name: Checkout latest code
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Test
      run: |
        python -m unittest
  web:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout latest code
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
    - run: npm install
      working-directory: web
    - run: npm test
      working-directory: web
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout latest code
      uses: actions/checkout@v2
    - run: docker build -t luna .
      